server:
  port: 8080
spring:
  application:
    name: codeconnectbackend
  datasource:
    url: jdbc:mysql://123.60.15.140:3306/codeconnect?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 123.60.15.140      # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: 123456
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 500MB
      max-request-size: 500MB
  rabbitmq:
    host: 123.60.15.140
    port: 5672
    username: root
    password: 123456
    virtual-host: my_vhost
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
  # 允许覆盖
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
minio:
  endpoint: http://123.60.15.140:9001
  accessKey: root
  secretKey: Software.
  bucketName1: questionimages
  bucketName2: testcasefiles
  bucketName3: useravatar
sa-token:
  # token前缀
  token-prefix: Bearer


